services:
  - type: web
    name: openwebui
    envs:
      groups:
        - GITHUB_OAUTH_CLIENT_ID: $GITHUB_OAUTH_CLIENT_ID
        - GITHUB_OAUTH_CLIENT_SECRET: $GITHUB_OAUTH_CLIENT_SECRET
        - FLASK_ENV: production
        - FLASK_APP: app:app
        - FLASK_RUN_HOST: 0.0.0.0
        - FLASK_RUN_PORT: 8000
    build:
      dockerfilePath: Dockerfile
    start:
      command: gunicorn app:app --bind 0.0.0.0:8000 --workers 4
